### ISSUE TITLE
BigQuery merges can be very expensive

### ISSUE THREAD

**Issue by judahrand** [jmriego/pipelinewise-target-bigquery#88]
BigQuery merges can be extremely expensive on large tables. I suggest adding the optional behavior which replicates what DBT's dynamic `insert_overwrite` strategy does as documented here: https://discourse.getdbt.com/t/bigquery-dbt-incremental-changes/982

The `partition_by` dictionary could be stored in the state file and written by PipelineWise FastSync like the `replication_method` and `replication_key` entries are currently.

**Comment by judahrand** [comment]
So I've confirmed that a MERGE which is currently 11.25GB per run can be reduced to (in my test case) ~390MB by using table partitioning: https://cloud.google.com/bigquery/docs/using-dml-with-partitioned-tables#using_a_filter_in_a_merge_condition

This seems like an obvious massive win!

**Comment by jmriego** [comment]
I totally agree with you and also think having those keys in the state file make sense. The only thing is that we need to be careful to also think about case in which the partition key and the incremental key are not the same.

There are many sources in which we might have a `last_modified_at` column that people use as the incremental key but maybe the PK can be something like `user_id` (in which case we can't do much to avoid a full scan) or it can be something like (`activity_date`, `activity_id`) in which we can scan the list of `activity_date` we have received in our incremental tap (so the full scan would be only on the newly received data) and use that as a filter for the MERGE.

We'll need to be careful to cover for many cases of changing PK, partition key, etc. That's not such a big deal on the FastSync as we can just replace the whole table with the new partitioning.
What do you think?

**Comment by judahrand** [comment]
You can't change the partition key on a BigQuery table without dropping the table anyway.

I actually have changed my thinking and think the Partition Key should be retrieved from BQ directly rather than stored in state. 

The partition can be created by FastSync depending on user config. After that it must be user managed. 

> maybe the PK can be something like user_id (in which case we can't do much to avoid a full scan) 

Partitioning by `user_id` is the thing to do here.

**Comment by jmriego** [comment]
For `pipelinewise-target-bigquery` I think it makes sense to completely ignore any partition information you might have on the tap config. The only thing this should do is to optimize the MERGE query as possible which is only really useful in some of the examples above.

If it's part of the incremental key it's easy to use that as a filter in the MERGE. If it's not (like having a `date_modified` as the incremental key but having `activity_date`, `activity_id` as the PK and partitioning by `activity_date`), you can probably still get a range or list of the `activity_date` that you should be merging on.

That's for the MERGE in this target. But then if you are planning on modifying FastSync there's quite a few cases you'd need to account for. You need to support integer range partitioning and date partitioning with configurable granularity so that you won't hit the limit of 4,000 partitions so easily.

At the end I'm not sure it makes much sense to make the FastSync be able to support all these partitioning cases and then any changes you make to the partition there be ignored when users would be expecting it to affect the table. For me it makes sense to only make the MERGE optimization here and all partition creation and config must be done manually. That's the same approach that Stitch and Fivetran are doing but it's different to what they do in Meltano: https://github.com/adswerve/target-bigquery#step-5-target-tables-config-file-set-up-partitioning-and-clustering

Does this make sense?

**Comment by judahrand** [comment]
I think it is always best to partition by an integer id column if possible in terms of reducing merge costs.

I don't see how partitioning by an incremental key would reduce the cost of merges? You need to partition by some immutable column. The two obvious options are 'created_at' and integer id columns.

**Comment by judahrand** [comment]
> For me it makes sense to only make the MERGE optimization here and all partition creation and config must be done manually.

Seems reasonable.

**Comment by judahrand** [comment]
@jmriego If you're interested in my progress on this so far you can look here: https://github.com/thread/pipelinewise-target-bigquery/pull/8

It supports both time and integer partitioning. The downside of it is that if the user has partitioned the table by a mutable column it will break the merge and mean that duplicates occur. I'd argue this is kind of user error, however. Perhaps there should be a `use_partition_pruning` in the config to allow users to disable the behaviour if they need an incompatible partition? 

I just need to add testing.
